# -*- coding: utf-8 -*-
"""Accuracy_graphs

Automatically generated by Colaboratory.

"""

import numpy as np
import matplotlib.pyplot as plt
 
  
# creating the dataset
data = {'Rad - 10 bins':56.9, 'HJPD - 10 bins':72.8, 'HOD - 8 bins':58.3}
courses = list(data.keys())
values = list(data.values())
c = ['royalblue','navy', 'blue']
  
fig = plt.figure(figsize = (10, 5))
 
# creating the bar plot
plt.bar(courses, values, color =c,
        width = 0.5)

plt.xlabel("Representation type")
plt.ylabel("Accuracy Percentage")
plt.title("Accuracy across bins")
plt.savefig("Accuracy.png")
